name: Build Docker Image

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  release:
    types:
      - published
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Image Tags
        id: generate-image-tags
        uses: docker/metadata-action@v6
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=ref,event=pr
            type=sha

      - name: Login to Container Registry
        if: github.event_name == 'release' || github.event_name == 'workflow_dispatch'
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v7
        with:
          context: .
          push: ${{ github.event_name == 'release' || github.event_name == 'workflow_dispatch' }}
          tags: ${{ steps.generate-image-tags.outputs.tags }}
          labels: ${{ steps.generate-image-tags.outputs.labels }}
